// Self-host the display fonts: downloads the latin woff2 subsets from Google Fonts into
// public/fonts/ and generates public/css/fonts.css (@font-face -> local files). Run when the
// font set changes. Removes the runtime dependency on the Google Fonts CDN (faster, no FOUT,
// no third-party request) and makes the offline visual captures render the real fonts.
import fs from 'fs';
import path from 'path';

// Families + weights as used by views/index.ejs.
const FAMILIES = [
  { name: 'Permanent Marker', param: 'Permanent+Marker', weights: [400] },
  { name: 'Fredoka One', param: 'Fredoka+One', weights: [400] },
  { name: 'Bungee', param: 'Bungee', weights: [400] },
  { name: 'Courier Prime', param: 'Courier+Prime:wght@400;700', weights: [400, 700] },
];
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120 Safari/537.36';
const slug = (s) => s.toLowerCase().replace(/\s+/g, '-');

const fontsDir = 'public/fonts';
fs.mkdirSync(fontsDir, { recursive: true });

const faces = [];
for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.param}&display=swap`;
  const css = await (await fetch(url, { headers: { 'User-Agent': UA } })).text();
  // Keep only the `latin` subset blocks (this app is English); each is preceded by /* latin */.
  const blocks = css.split('/*').map((b) => '/*' + b);
  for (const block of blocks) {
    if (!/^\/\*\s*latin\s*\*\//.test(block)) continue;
    const weight = Number(block.match(/font-weight:\s*(\d+)/)?.[1] ?? 400);
    const src = block.match(/src:\s*url\(([^)]+)\)/)?.[1];
    if (!src || !fam.weights.includes(weight)) continue;
    const file = `${slug(fam.name)}-${weight}.woff2`;
    const buf = Buffer.from(
      await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer(),
    );
    fs.writeFileSync(path.join(fontsDir, file), buf);
    faces.push(
      `@font-face {\n  font-family: '${fam.name}';\n  font-style: normal;\n  font-weight: ${weight};\n  font-display: block;\n  src: url('/fonts/${file}') format('woff2');\n}`,
    );
    console.log(`  ${file} (${buf.length} bytes)`);
  }
}

const header =
  '/* Self-hosted display fonts (latin subset). Generated by scripts/fetch-fonts.mjs -\n' +
  '   do not edit by hand. Fonts are SIL OFL licensed; see Google Fonts. */\n';
fs.writeFileSync('public/css/fonts.css', header + faces.join('\n\n') + '\n');
console.log(`\nwrote public/css/fonts.css (${faces.length} @font-face rules)`);
